name: mobile_walkeeg
description: WalkEEG BLE real-time waveform viewer
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  shared_preferences: ^2.3.3
  http: ^1.2.2
  aws_client: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
